#!/bin/bash
# setup.sh — Interactive & Automated Wizard to generate all configuration files
# Prompts for environment variables and generates valid JSON, HCL, and SSM files.

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
SSM_DIR="${REPO_ROOT}/ssm"
TERRAFORM_DIR="${REPO_ROOT}/terraform"

NON_INTERACTIVE=false
if [[ "${1:-}" == "--non-interactive" || "${NON_INTERACTIVE:-false}" == "true" ]]; then
    NON_INTERACTIVE=true
fi

echo "=========================================================="
echo "      EC2 Stateless IPsec VPN Gateway Setup Wizard        "
echo "=========================================================="
echo ""

prompt() {
    local var_name="$1"
    local prompt_text="$2"
    local default_val="$3"
    local val=""

    if [[ "$NON_INTERACTIVE" == "true" ]]; then
        val="${!var_name:-$default_val}"
    else
        read -rp "${prompt_text} [default: ${default_val}]: " input_val
        val="${input_val:-$default_val}"
    fi

    printf -v "$var_name" "%s" "$val"
}

# 1. AWS Basic Infrastructure Configuration
echo "--- 1. AWS Basic Infrastructure ---"
prompt AWS_REGION "AWS Region" "us-east-1"
prompt VPC_ID "VPC ID (e.g. vpc-0123456789abcdef0)" "vpc-0123456789abcdef0"
prompt PRIMARY_SUBNET_ID "Primary Subnet ID (e.g. subnet-0123456789abcdef0)" "subnet-0123456789abcdef0"
prompt SECONDARY_SUBNET_ID "Secondary Subnet ID for Multi-AZ (optional)" "subnet-0fedcba9876543210"
prompt SECURITY_GROUP_ID "Security Group ID (e.g. sg-0123456789abcdef0)" "sg-0123456789abcdef0"
prompt KEY_NAME "SSH Key Pair Name" "my-key-pair"
prompt AMI_ID "Amazon Linux 2023 ARM64 AMI ID" "ami-0123456789abcdef0"

echo ""
echo "--- 2. Instance & Web Service Configuration ---"
prompt SYSTEM_HOSTNAME "System Hostname" "VPN-Gateway-Instance"
prompt HTTPD_SERVER_NAME "Apache Web Service ServerName (domain)" "ws.example.com"
prompt REPO_WEBSERVICE_URL "CodeCommit Repository URL for webservice" "https://git-codecommit.${AWS_REGION}.amazonaws.com/v1/repos/webservice"
prompt REPO_PLATAFORMA_URL "CodeCommit Repository URL for plataforma" "https://git-codecommit.${AWS_REGION}.amazonaws.com/v1/repos/plataforma"

echo ""
echo "--- 3. Elastic IPs & Remote IPsec Peers ---"
prompt PRIMARY_EIP_ALLOC "Primary EIP Allocation ID (e.g. eipalloc-0123456789abcdef0)" "eipalloc-0123456789abcdef0"
prompt SECONDARY_EIP_ALLOC "Secondary EIP Allocation ID (e.g. eipalloc-0fedcba9876543210)" "eipalloc-0fedcba9876543210"
prompt REMOTE_GATEWAY_IP "Remote IPsec Gateway IP" "192.0.2.253"
prompt REMOTE_HOSTS_IPS "Remote IPsec Host IPs (comma-separated)" "192.0.2.10,192.0.2.11,192.0.2.12"

DEFAULT_PSK="$(LC_ALL=C tr -dc 'A-Za-z0-9!@#%^&*' < /dev/urandom | head -c 32 || echo "SecureIPsecPSK123!@#AutoGenerated")"
prompt IPSEC_PSK "IPsec Pre-Shared Key (PSK)" "$DEFAULT_PSK"

echo ""
echo "--- 4. Load Balancer Integration ---"
prompt CREATE_NLB "Create new Network Load Balancer (true/false)" "true"
if [[ "$CREATE_NLB" == "false" ]]; then
    prompt EXISTING_TG_ARN "Existing Target Group ARN" ""
else
    EXISTING_TG_ARN=""
fi

echo ""
echo "=========================================================="
echo " Generating Configuration Files..."
echo "=========================================================="

# Create directories
mkdir -p "$SSM_DIR" "$TERRAFORM_DIR"

# 1. ssm/bootstrap-config.json
cat > "${SSM_DIR}/bootstrap-config.json" <<EOF
{
  "hostname": "${SYSTEM_HOSTNAME}",
  "httpd_server_name": "${HTTPD_SERVER_NAME}",
  "primary_eip_allocation_id": "${PRIMARY_EIP_ALLOC}",
  "secondary_eip_allocation_id": "${SECONDARY_EIP_ALLOC}",
  "repositories": [
    {
      "url": "${REPO_WEBSERVICE_URL}",
      "directory": "/var/www/webservice"
    },
    {
      "url": "${REPO_PLATAFORMA_URL}",
      "directory": "/var/www/plataforma"
    }
  ]
}
EOF
echo "✔ Generated ssm/bootstrap-config.json"

# 2. ssm/ipsec.conf
cat > "${SSM_DIR}/ipsec.conf" <<'EOF'
conn vpn-connection
    type=tunnel
    ikev2=insist
    authby=secret

    left=%defaultroute
    leftid=${PRIMARY_PUBLIC_IP}
    leftsubnet=${LOCAL_ENCRYPTION_DOMAIN}/32
    leftsourceip=${LOCAL_ENCRYPTION_DOMAIN}

    right=${REMOTE_GATEWAY}
    rightid=${REMOTE_GATEWAY}
    rightsubnets=${REMOTE_SUBNETS}

    ike=aes256-sha2_256;modp2048
    esp=aes256-sha2_256
    pfs=no

    ikelifetime=28800s
    salifetime=3600s
    rekeymargin=300s
    rekeyfuzz=0%
    keyingtries=%forever

    dpddelay=30s
    dpdaction=restart

    auto=start
EOF
echo "✔ Generated ssm/ipsec.conf"

# 3. ssm/vhost.conf
cat > "${SSM_DIR}/vhost.conf" <<'EOF'
<VirtualHost *:80>
    ServerName ${HTTPD_SERVER_NAME}

    ServerAlias ${PRIMARY_PUBLIC_IP} ${SECONDARY_PUBLIC_IP} ${PRIMARY_PRIVATE_IP} ${SECONDARY_PRIVATE_IP}

    DocumentRoot /var/www/webservice/ws
    ServerAdmin admin@${HTTPD_SERVER_NAME}

    ErrorLog /var/log/httpd/${HTTPD_SERVER_NAME}_error_log

    SetEnvIf Request_URI "^/healthCheck\.php$" nlb_healthcheck

    CustomLog /var/log/httpd/${HTTPD_SERVER_NAME}_access_log combined env=!nlb_healthcheck

    <Directory "/var/www/webservice/ws">
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
EOF
echo "✔ Generated ssm/vhost.conf"

# 4. ssm/psk
printf '%s' "$IPSEC_PSK" > "${SSM_DIR}/psk"
echo "✔ Generated ssm/psk"

# 5. ssm/remote-gateway
printf '%s' "$REMOTE_GATEWAY_IP" > "${SSM_DIR}/remote-gateway"
echo "✔ Generated ssm/remote-gateway"

# 6. ssm/remote-hosts
printf '%s' "$REMOTE_HOSTS_IPS" > "${SSM_DIR}/remote-hosts"
echo "✔ Generated ssm/remote-hosts"

# 7. terraform/terraform.tfvars
cat > "${TERRAFORM_DIR}/terraform.tfvars" <<EOF
# Generated automatically by setup.sh
region = "${AWS_REGION}"
ami_id = "${AMI_ID}"

instance_type     = "t4g.micro"
vpc_id            = "${VPC_ID}"
subnet_id         = "${PRIMARY_SUBNET_ID}"
subnet_ids        = ["${PRIMARY_SUBNET_ID}", "${SECONDARY_SUBNET_ID}"]
security_group_id = "${SECURITY_GROUP_ID}"
key_name          = "${KEY_NAME}"

iam_instance_profile = "EC2-VPN-Gateway-Role"
instance_name        = "${SYSTEM_HOSTNAME}"

asg_min_size         = 1
asg_max_size         = 1
asg_desired_capacity = 1

create_load_balancer      = ${CREATE_NLB}
existing_target_group_arn = "${EXISTING_TG_ARN}"

tags = {
  Project     = "vpn-gateway"
  Environment = "production"
}
EOF
echo "✔ Generated terraform/terraform.tfvars"

echo ""
echo "=========================================================="
echo " Setup completed successfully!"
echo " Next step: Deploy with Terraform"
echo "   cd terraform && terraform init && terraform apply"
echo "=========================================================="
